// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: server_grpc/proto/v1/product/product.proto

package server_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductToSave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=Product_name,json=ProductName,proto3" json:"Product_name,omitempty"`
	ProductGroup  string                 `protobuf:"bytes,2,opt,name=Product_group,json=ProductGroup,proto3" json:"Product_group,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductToSave) Reset() {
	*x = ProductToSave{}
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductToSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductToSave) ProtoMessage() {}

func (x *ProductToSave) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductToSave.ProtoReflect.Descriptor instead.
func (*ProductToSave) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductToSave) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductToSave) GetProductGroup() string {
	if x != nil {
		return x.ProductGroup
	}
	return ""
}

func (x *ProductToSave) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ProductToSave) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductToSave) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProductUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=Product_name,json=ProductName,proto3" json:"Product_name,omitempty"`
	ProductGroup  string                 `protobuf:"bytes,2,opt,name=Product_group,json=ProductGroup,proto3" json:"Product_group,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdate) Reset() {
	*x = ProductUpdate{}
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdate) ProtoMessage() {}

func (x *ProductUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdate.ProtoReflect.Descriptor instead.
func (*ProductUpdate) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductUpdate) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductUpdate) GetProductGroup() string {
	if x != nil {
		return x.ProductGroup
	}
	return ""
}

func (x *ProductUpdate) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ProductUpdate) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductUpdate) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductByRequestID struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductToUpdate *ProductUpdate         `protobuf:"bytes,2,opt,name=productToUpdate,proto3" json:"productToUpdate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProductByRequestID) Reset() {
	*x = UpdateProductByRequestID{}
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductByRequestID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductByRequestID) ProtoMessage() {}

func (x *UpdateProductByRequestID) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductByRequestID.ProtoReflect.Descriptor instead.
func (*UpdateProductByRequestID) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductByRequestID) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductByRequestID) GetProductToUpdate() *ProductUpdate {
	if x != nil {
		return x.ProductToUpdate
	}
	return nil
}

type ProductDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=Product_name,json=ProductName,proto3" json:"Product_name,omitempty"`
	ProductGroup  string                 `protobuf:"bytes,3,opt,name=Product_group,json=ProductGroup,proto3" json:"Product_group,omitempty"`
	Image         []byte                 `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDomain) Reset() {
	*x = ProductDomain{}
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDomain) ProtoMessage() {}

func (x *ProductDomain) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDomain.ProtoReflect.Descriptor instead.
func (*ProductDomain) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductDomain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductDomain) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductDomain) GetProductGroup() string {
	if x != nil {
		return x.ProductGroup
	}
	return ""
}

func (x *ProductDomain) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ProductDomain) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductDomain) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type RequestProductID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProductID) Reset() {
	*x = RequestProductID{}
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProductID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProductID) ProtoMessage() {}

func (x *RequestProductID) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProductID.ProtoReflect.Descriptor instead.
func (*RequestProductID) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *RequestProductID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestProductName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProductName) Reset() {
	*x = RequestProductName{}
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProductName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProductName) ProtoMessage() {}

func (x *RequestProductName) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProductName.ProtoReflect.Descriptor instead.
func (*RequestProductName) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *RequestProductName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_server_grpc_proto_v1_product_product_proto protoreflect.FileDescriptor

const file_server_grpc_proto_v1_product_product_proto_rawDesc = "" +
	"\n" +
	"*server_grpc/proto/v1/product/product.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x01\n" +
	"\rProductToSave\x12!\n" +
	"\fProduct_name\x18\x01 \x01(\tR\vProductName\x12#\n" +
	"\rProduct_group\x18\x02 \x01(\tR\fProductGroup\x12\x14\n" +
	"\x05Image\x18\x03 \x01(\fR\x05Image\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x03R\x05Price\"\x99\x01\n" +
	"\rProductUpdate\x12!\n" +
	"\fProduct_name\x18\x01 \x01(\tR\vProductName\x12#\n" +
	"\rProduct_group\x18\x02 \x01(\tR\fProductGroup\x12\x14\n" +
	"\x05Image\x18\x03 \x01(\fR\x05Image\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x03R\x05Price\"s\n" +
	"\x18UpdateProductByRequestID\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x128\n" +
	"\x0fproductToUpdate\x18\x02 \x01(\v2\x0e.ProductUpdateR\x0fproductToUpdate\"\xa9\x01\n" +
	"\rProductDomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fProduct_name\x18\x02 \x01(\tR\vProductName\x12#\n" +
	"\rProduct_group\x18\x03 \x01(\tR\fProductGroup\x12\x14\n" +
	"\x05Image\x18\x04 \x01(\fR\x05Image\x12\x14\n" +
	"\x05Stock\x18\x05 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\x06 \x01(\x03R\x05Price\"\"\n" +
	"\x10RequestProductID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"(\n" +
	"\x12RequestProductName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xc6\x02\n" +
	"\x0eProductService\x12&\n" +
	"\x04Save\x12\x0e.ProductToSave\x1a\x0e.ProductDomain\x12,\n" +
	"\aGetById\x12\x11.RequestProductID\x1a\x0e.ProductDomain\x120\n" +
	"\tGetByName\x12\x13.RequestProductName\x1a\x0e.ProductDomain\x122\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x0e.ProductDomain0\x01\x12?\n" +
	"\n" +
	"UpdateById\x12\x19.UpdateProductByRequestID\x1a\x16.google.protobuf.Empty\x127\n" +
	"\n" +
	"DeleteById\x12\x11.RequestProductID\x1a\x16.google.protobuf.EmptyB Z\x1eerp-2c/api-gateway/server_grpcb\x06proto3"

var (
	file_server_grpc_proto_v1_product_product_proto_rawDescOnce sync.Once
	file_server_grpc_proto_v1_product_product_proto_rawDescData []byte
)

func file_server_grpc_proto_v1_product_product_proto_rawDescGZIP() []byte {
	file_server_grpc_proto_v1_product_product_proto_rawDescOnce.Do(func() {
		file_server_grpc_proto_v1_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpc_proto_v1_product_product_proto_rawDesc), len(file_server_grpc_proto_v1_product_product_proto_rawDesc)))
	})
	return file_server_grpc_proto_v1_product_product_proto_rawDescData
}

var file_server_grpc_proto_v1_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_grpc_proto_v1_product_product_proto_goTypes = []any{
	(*ProductToSave)(nil),            // 0: ProductToSave
	(*ProductUpdate)(nil),            // 1: ProductUpdate
	(*UpdateProductByRequestID)(nil), // 2: UpdateProductByRequestID
	(*ProductDomain)(nil),            // 3: ProductDomain
	(*RequestProductID)(nil),         // 4: RequestProductID
	(*RequestProductName)(nil),       // 5: RequestProductName
	(*emptypb.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_server_grpc_proto_v1_product_product_proto_depIdxs = []int32{
	1, // 0: UpdateProductByRequestID.productToUpdate:type_name -> ProductUpdate
	0, // 1: ProductService.Save:input_type -> ProductToSave
	4, // 2: ProductService.GetById:input_type -> RequestProductID
	5, // 3: ProductService.GetByName:input_type -> RequestProductName
	6, // 4: ProductService.GetAll:input_type -> google.protobuf.Empty
	2, // 5: ProductService.UpdateById:input_type -> UpdateProductByRequestID
	4, // 6: ProductService.DeleteById:input_type -> RequestProductID
	3, // 7: ProductService.Save:output_type -> ProductDomain
	3, // 8: ProductService.GetById:output_type -> ProductDomain
	3, // 9: ProductService.GetByName:output_type -> ProductDomain
	3, // 10: ProductService.GetAll:output_type -> ProductDomain
	6, // 11: ProductService.UpdateById:output_type -> google.protobuf.Empty
	6, // 12: ProductService.DeleteById:output_type -> google.protobuf.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_grpc_proto_v1_product_product_proto_init() }
func file_server_grpc_proto_v1_product_product_proto_init() {
	if File_server_grpc_proto_v1_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpc_proto_v1_product_product_proto_rawDesc), len(file_server_grpc_proto_v1_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpc_proto_v1_product_product_proto_goTypes,
		DependencyIndexes: file_server_grpc_proto_v1_product_product_proto_depIdxs,
		MessageInfos:      file_server_grpc_proto_v1_product_product_proto_msgTypes,
	}.Build()
	File_server_grpc_proto_v1_product_product_proto = out.File
	file_server_grpc_proto_v1_product_product_proto_goTypes = nil
	file_server_grpc_proto_v1_product_product_proto_depIdxs = nil
}
