  syntax = "proto3";
  option go_package = "erp-2c/v1/delivery-grpc";


  service DeliveryService {
      rpc Save(DeliveryItemsDomain) returns (DeliveryItemsDomain);
      rpc GetById(RequestDeliveryID) returns (DeliveryItemsDomain);
      rpc GetAll(EmptyRequest) returns (stream DeliveryItemListDomain);
//      rpc GetByName(RequestDeliveryName) returns (DeliveryItemsDomain);
      rpc UpdateById(UpdateStatus) returns (EmptyResponse);
      rpc DeleteById(RequestDeliveryID) returns (EmptyResponse);
  }

      message EmptyRequest {}
      message EmptyResponse {}

      message RequestDeliveryID {
          int64 deliveryId = 1;
      }

     message RequestDeliveryName {
          string deliveryName = 1;
      }

      message DeliveryStatus {
        string status = 1;
      }

      message DeliverDomain {
        int64 ID = 1;
        string Recipient = 2;
        string Address = 3;
        DeliveryStatus Status = 4;
        int64 CreatedA = 5;
        int64 UserID = 6;
        int64 DeliverAmount = 7;
      }

      message ItemDomain {
        int64 DeliveryID = 1;
        int64 ProductID = 2;
        int64 ItemPrice = 3;
        int64 Quantity = 4;
        int64 ItemAmount = 5;
      }

      message DeliveryItemsDomain {
        DeliverDomain delivery = 1;
        repeated  ItemDomain Items = 2;
      }

      message DeliveryItemListDomain {
        repeated DeliveryItemsDomain deliveryItemsDomain = 1;
      }

      message UpdateStatus {
        int64 DeliveryId = 1;
        DeliveryStatus Status = 2;
      }

