// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: server_grpc/proto/v1/notify/notify.proto

package server_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    int64                  `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_server_grpc_proto_v1_notify_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_notify_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_notify_notify_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_server_grpc_proto_v1_notify_notify_proto protoreflect.FileDescriptor

const file_server_grpc_proto_v1_notify_notify_proto_rawDesc = "" +
	"\n" +
	"(server_grpc/proto/v1/notify/notify.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x01\n" +
	"\fNotification\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\x03R\n" +
	"deliveryId\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId2F\n" +
	"\rNotifyService\x125\n" +
	"\n" +
	"SendNotify\x12\r.Notification\x1a\x16.google.protobuf.Empty(\x01B Z\x1eerp-2c/api-gateway/server_grpcb\x06proto3"

var (
	file_server_grpc_proto_v1_notify_notify_proto_rawDescOnce sync.Once
	file_server_grpc_proto_v1_notify_notify_proto_rawDescData []byte
)

func file_server_grpc_proto_v1_notify_notify_proto_rawDescGZIP() []byte {
	file_server_grpc_proto_v1_notify_notify_proto_rawDescOnce.Do(func() {
		file_server_grpc_proto_v1_notify_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpc_proto_v1_notify_notify_proto_rawDesc), len(file_server_grpc_proto_v1_notify_notify_proto_rawDesc)))
	})
	return file_server_grpc_proto_v1_notify_notify_proto_rawDescData
}

var file_server_grpc_proto_v1_notify_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_grpc_proto_v1_notify_notify_proto_goTypes = []any{
	(*Notification)(nil),          // 0: Notification
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_server_grpc_proto_v1_notify_notify_proto_depIdxs = []int32{
	1, // 0: Notification.createdAt:type_name -> google.protobuf.Timestamp
	0, // 1: NotifyService.SendNotify:input_type -> Notification
	2, // 2: NotifyService.SendNotify:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_grpc_proto_v1_notify_notify_proto_init() }
func file_server_grpc_proto_v1_notify_notify_proto_init() {
	if File_server_grpc_proto_v1_notify_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpc_proto_v1_notify_notify_proto_rawDesc), len(file_server_grpc_proto_v1_notify_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpc_proto_v1_notify_notify_proto_goTypes,
		DependencyIndexes: file_server_grpc_proto_v1_notify_notify_proto_depIdxs,
		MessageInfos:      file_server_grpc_proto_v1_notify_notify_proto_msgTypes,
	}.Build()
	File_server_grpc_proto_v1_notify_notify_proto = out.File
	file_server_grpc_proto_v1_notify_notify_proto_goTypes = nil
	file_server_grpc_proto_v1_notify_notify_proto_depIdxs = nil
}
