// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: server_grpc/proto/v1/delivery/delivery.proto

package server_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_Save_FullMethodName        = "/DeliveryService/Save"
	DeliveryService_GetById_FullMethodName     = "/DeliveryService/GetById"
	DeliveryService_GetByStatus_FullMethodName = "/DeliveryService/GetByStatus"
	DeliveryService_GetAll_FullMethodName      = "/DeliveryService/GetAll"
	DeliveryService_UpdateById_FullMethodName  = "/DeliveryService/UpdateById"
	DeliveryService_DeleteById_FullMethodName  = "/DeliveryService/DeleteById"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	Save(ctx context.Context, in *DeliveryItemsDomain, opts ...grpc.CallOption) (*DeliveryItemsDomain, error)
	GetById(ctx context.Context, in *RequestDeliveryID, opts ...grpc.CallOption) (*DeliveryItemsDomain, error)
	GetByStatus(ctx context.Context, in *DeliveryStatus, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliveryItemsDomain], error)
	GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliveryItemsDomain], error)
	UpdateById(ctx context.Context, in *UpdateStatus, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteById(ctx context.Context, in *RequestDeliveryID, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) Save(ctx context.Context, in *DeliveryItemsDomain, opts ...grpc.CallOption) (*DeliveryItemsDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryItemsDomain)
	err := c.cc.Invoke(ctx, DeliveryService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetById(ctx context.Context, in *RequestDeliveryID, opts ...grpc.CallOption) (*DeliveryItemsDomain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryItemsDomain)
	err := c.cc.Invoke(ctx, DeliveryService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetByStatus(ctx context.Context, in *DeliveryStatus, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliveryItemsDomain], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[0], DeliveryService_GetByStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeliveryStatus, DeliveryItemsDomain]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_GetByStatusClient = grpc.ServerStreamingClient[DeliveryItemsDomain]

func (c *deliveryServiceClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeliveryItemsDomain], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeliveryService_ServiceDesc.Streams[1], DeliveryService_GetAll_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, DeliveryItemsDomain]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_GetAllClient = grpc.ServerStreamingClient[DeliveryItemsDomain]

func (c *deliveryServiceClient) UpdateById(ctx context.Context, in *UpdateStatus, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) DeleteById(ctx context.Context, in *RequestDeliveryID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DeliveryService_DeleteById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	Save(context.Context, *DeliveryItemsDomain) (*DeliveryItemsDomain, error)
	GetById(context.Context, *RequestDeliveryID) (*DeliveryItemsDomain, error)
	GetByStatus(*DeliveryStatus, grpc.ServerStreamingServer[DeliveryItemsDomain]) error
	GetAll(*emptypb.Empty, grpc.ServerStreamingServer[DeliveryItemsDomain]) error
	UpdateById(context.Context, *UpdateStatus) (*emptypb.Empty, error)
	DeleteById(context.Context, *RequestDeliveryID) (*emptypb.Empty, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) Save(context.Context, *DeliveryItemsDomain) (*DeliveryItemsDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedDeliveryServiceServer) GetById(context.Context, *RequestDeliveryID) (*DeliveryItemsDomain, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedDeliveryServiceServer) GetByStatus(*DeliveryStatus, grpc.ServerStreamingServer[DeliveryItemsDomain]) error {
	return status.Error(codes.Unimplemented, "method GetByStatus not implemented")
}
func (UnimplementedDeliveryServiceServer) GetAll(*emptypb.Empty, grpc.ServerStreamingServer[DeliveryItemsDomain]) error {
	return status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateById(context.Context, *UpdateStatus) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateById not implemented")
}
func (UnimplementedDeliveryServiceServer) DeleteById(context.Context, *RequestDeliveryID) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteById not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryItemsDomain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).Save(ctx, req.(*DeliveryItemsDomain))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeliveryID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetById(ctx, req.(*RequestDeliveryID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetByStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeliveryStatus)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).GetByStatus(m, &grpc.GenericServerStream[DeliveryStatus, DeliveryItemsDomain]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_GetByStatusServer = grpc.ServerStreamingServer[DeliveryItemsDomain]

func _DeliveryService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeliveryServiceServer).GetAll(m, &grpc.GenericServerStream[emptypb.Empty, DeliveryItemsDomain]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeliveryService_GetAllServer = grpc.ServerStreamingServer[DeliveryItemsDomain]

func _DeliveryService_UpdateById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateById(ctx, req.(*UpdateStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_DeleteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeliveryID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).DeleteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_DeleteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).DeleteById(ctx, req.(*RequestDeliveryID))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _DeliveryService_Save_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _DeliveryService_GetById_Handler,
		},
		{
			MethodName: "UpdateById",
			Handler:    _DeliveryService_UpdateById_Handler,
		},
		{
			MethodName: "DeleteById",
			Handler:    _DeliveryService_DeleteById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetByStatus",
			Handler:       _DeliveryService_GetByStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _DeliveryService_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server_grpc/proto/v1/delivery/delivery.proto",
}
