// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: server_grpc/proto/v1/delivery/delivery.proto

package server_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDeliveryID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    int64                  `protobuf:"varint,1,opt,name=Delivery_id,json=DeliveryId,proto3" json:"Delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeliveryID) Reset() {
	*x = RequestDeliveryID{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeliveryID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeliveryID) ProtoMessage() {}

func (x *RequestDeliveryID) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeliveryID.ProtoReflect.Descriptor instead.
func (*RequestDeliveryID) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDeliveryID) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

type RequestDeliveryName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryName  string                 `protobuf:"bytes,1,opt,name=Delivery_name,json=DeliveryName,proto3" json:"Delivery_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeliveryName) Reset() {
	*x = RequestDeliveryName{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeliveryName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeliveryName) ProtoMessage() {}

func (x *RequestDeliveryName) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeliveryName.ProtoReflect.Descriptor instead.
func (*RequestDeliveryName) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDeliveryName) GetDeliveryName() string {
	if x != nil {
		return x.DeliveryName
	}
	return ""
}

type DeliveryStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatus) Reset() {
	*x = DeliveryStatus{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatus) ProtoMessage() {}

func (x *DeliveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatus.ProtoReflect.Descriptor instead.
func (*DeliveryStatus) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeliverDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Status        *DeliveryStatus        `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UserId        int64                  `protobuf:"varint,6,opt,name=User_id,json=UserId,proto3" json:"User_id,omitempty"`
	DeliverAmount int64                  `protobuf:"varint,7,opt,name=Deliver_amount,json=DeliverAmount,proto3" json:"Deliver_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverDomain) Reset() {
	*x = DeliverDomain{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverDomain) ProtoMessage() {}

func (x *DeliverDomain) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverDomain.ProtoReflect.Descriptor instead.
func (*DeliverDomain) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *DeliverDomain) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DeliverDomain) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *DeliverDomain) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeliverDomain) GetStatus() *DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DeliverDomain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeliverDomain) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeliverDomain) GetDeliverAmount() int64 {
	if x != nil {
		return x.DeliverAmount
	}
	return 0
}

type ItemDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    int64                  `protobuf:"varint,1,opt,name=Delivery_id,json=DeliveryId,proto3" json:"Delivery_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=Product_id,json=ProductId,proto3" json:"Product_id,omitempty"`
	ItemPrice     int64                  `protobuf:"varint,3,opt,name=ItemPrice,proto3" json:"ItemPrice,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	ItemAmount    int64                  `protobuf:"varint,5,opt,name=ItemAmount,proto3" json:"ItemAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDomain) Reset() {
	*x = ItemDomain{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDomain) ProtoMessage() {}

func (x *ItemDomain) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDomain.ProtoReflect.Descriptor instead.
func (*ItemDomain) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *ItemDomain) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *ItemDomain) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ItemDomain) GetItemPrice() int64 {
	if x != nil {
		return x.ItemPrice
	}
	return 0
}

func (x *ItemDomain) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemDomain) GetItemAmount() int64 {
	if x != nil {
		return x.ItemAmount
	}
	return 0
}

type DeliveryItemsDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliverDomain         `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Items         []*ItemDomain          `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryItemsDomain) Reset() {
	*x = DeliveryItemsDomain{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryItemsDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryItemsDomain) ProtoMessage() {}

func (x *DeliveryItemsDomain) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryItemsDomain.ProtoReflect.Descriptor instead.
func (*DeliveryItemsDomain) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryItemsDomain) GetDelivery() *DeliverDomain {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *DeliveryItemsDomain) GetItems() []*ItemDomain {
	if x != nil {
		return x.Items
	}
	return nil
}

// todo use enum
type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    int64                  `protobuf:"varint,1,opt,name=Delivery_id,json=DeliveryId,proto3" json:"Delivery_id,omitempty"`
	Status        *DeliveryStatus        `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatus) GetDeliveryId() int64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *UpdateStatus) GetStatus() *DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_server_grpc_proto_v1_delivery_delivery_proto protoreflect.FileDescriptor

const file_server_grpc_proto_v1_delivery_delivery_proto_rawDesc = "" +
	"\n" +
	",server_grpc/proto/v1/delivery/delivery.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x11RequestDeliveryID\x12\x1f\n" +
	"\vDelivery_id\x18\x01 \x01(\x03R\n" +
	"DeliveryId\":\n" +
	"\x13RequestDeliveryName\x12#\n" +
	"\rDelivery_name\x18\x01 \x01(\tR\fDeliveryName\"(\n" +
	"\x0eDeliveryStatus\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"\xfa\x01\n" +
	"\rDeliverDomain\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tRecipient\x18\x02 \x01(\tR\tRecipient\x12\x18\n" +
	"\aAddress\x18\x03 \x01(\tR\aAddress\x12'\n" +
	"\x06Status\x18\x04 \x01(\v2\x0f.DeliveryStatusR\x06Status\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x17\n" +
	"\aUser_id\x18\x06 \x01(\x03R\x06UserId\x12%\n" +
	"\x0eDeliver_amount\x18\a \x01(\x03R\rDeliverAmount\"\xa6\x01\n" +
	"\n" +
	"ItemDomain\x12\x1f\n" +
	"\vDelivery_id\x18\x01 \x01(\x03R\n" +
	"DeliveryId\x12\x1d\n" +
	"\n" +
	"Product_id\x18\x02 \x01(\x03R\tProductId\x12\x1c\n" +
	"\tItemPrice\x18\x03 \x01(\x03R\tItemPrice\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x03R\bQuantity\x12\x1e\n" +
	"\n" +
	"ItemAmount\x18\x05 \x01(\x03R\n" +
	"ItemAmount\"d\n" +
	"\x13DeliveryItemsDomain\x12*\n" +
	"\bdelivery\x18\x01 \x01(\v2\x0e.DeliverDomainR\bdelivery\x12!\n" +
	"\x05Items\x18\x02 \x03(\v2\v.ItemDomainR\x05Items\"X\n" +
	"\fUpdateStatus\x12\x1f\n" +
	"\vDelivery_id\x18\x01 \x01(\x03R\n" +
	"DeliveryId\x12'\n" +
	"\x06Status\x18\x02 \x01(\v2\x0f.DeliveryStatusR\x06Status2\xdb\x02\n" +
	"\x0fDeliveryService\x122\n" +
	"\x04Save\x12\x14.DeliveryItemsDomain\x1a\x14.DeliveryItemsDomain\x123\n" +
	"\aGetById\x12\x12.RequestDeliveryID\x1a\x14.DeliveryItemsDomain\x126\n" +
	"\vGetByStatus\x12\x0f.DeliveryStatus\x1a\x14.DeliveryItemsDomain0\x01\x128\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x14.DeliveryItemsDomain0\x01\x123\n" +
	"\n" +
	"UpdateById\x12\r.UpdateStatus\x1a\x16.google.protobuf.Empty\x128\n" +
	"\n" +
	"DeleteById\x12\x12.RequestDeliveryID\x1a\x16.google.protobuf.EmptyB%Z#erp-2c/delivery-service/server_grpcb\x06proto3"

var (
	file_server_grpc_proto_v1_delivery_delivery_proto_rawDescOnce sync.Once
	file_server_grpc_proto_v1_delivery_delivery_proto_rawDescData []byte
)

func file_server_grpc_proto_v1_delivery_delivery_proto_rawDescGZIP() []byte {
	file_server_grpc_proto_v1_delivery_delivery_proto_rawDescOnce.Do(func() {
		file_server_grpc_proto_v1_delivery_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpc_proto_v1_delivery_delivery_proto_rawDesc), len(file_server_grpc_proto_v1_delivery_delivery_proto_rawDesc)))
	})
	return file_server_grpc_proto_v1_delivery_delivery_proto_rawDescData
}

var file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_grpc_proto_v1_delivery_delivery_proto_goTypes = []any{
	(*RequestDeliveryID)(nil),     // 0: RequestDeliveryID
	(*RequestDeliveryName)(nil),   // 1: RequestDeliveryName
	(*DeliveryStatus)(nil),        // 2: DeliveryStatus
	(*DeliverDomain)(nil),         // 3: DeliverDomain
	(*ItemDomain)(nil),            // 4: ItemDomain
	(*DeliveryItemsDomain)(nil),   // 5: DeliveryItemsDomain
	(*UpdateStatus)(nil),          // 6: UpdateStatus
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_server_grpc_proto_v1_delivery_delivery_proto_depIdxs = []int32{
	2,  // 0: DeliverDomain.Status:type_name -> DeliveryStatus
	7,  // 1: DeliverDomain.CreatedAt:type_name -> google.protobuf.Timestamp
	3,  // 2: DeliveryItemsDomain.delivery:type_name -> DeliverDomain
	4,  // 3: DeliveryItemsDomain.Items:type_name -> ItemDomain
	2,  // 4: UpdateStatus.Status:type_name -> DeliveryStatus
	5,  // 5: DeliveryService.Save:input_type -> DeliveryItemsDomain
	0,  // 6: DeliveryService.GetById:input_type -> RequestDeliveryID
	2,  // 7: DeliveryService.GetByStatus:input_type -> DeliveryStatus
	8,  // 8: DeliveryService.GetAll:input_type -> google.protobuf.Empty
	6,  // 9: DeliveryService.UpdateById:input_type -> UpdateStatus
	0,  // 10: DeliveryService.DeleteById:input_type -> RequestDeliveryID
	5,  // 11: DeliveryService.Save:output_type -> DeliveryItemsDomain
	5,  // 12: DeliveryService.GetById:output_type -> DeliveryItemsDomain
	5,  // 13: DeliveryService.GetByStatus:output_type -> DeliveryItemsDomain
	5,  // 14: DeliveryService.GetAll:output_type -> DeliveryItemsDomain
	8,  // 15: DeliveryService.UpdateById:output_type -> google.protobuf.Empty
	8,  // 16: DeliveryService.DeleteById:output_type -> google.protobuf.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_server_grpc_proto_v1_delivery_delivery_proto_init() }
func file_server_grpc_proto_v1_delivery_delivery_proto_init() {
	if File_server_grpc_proto_v1_delivery_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpc_proto_v1_delivery_delivery_proto_rawDesc), len(file_server_grpc_proto_v1_delivery_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpc_proto_v1_delivery_delivery_proto_goTypes,
		DependencyIndexes: file_server_grpc_proto_v1_delivery_delivery_proto_depIdxs,
		MessageInfos:      file_server_grpc_proto_v1_delivery_delivery_proto_msgTypes,
	}.Build()
	File_server_grpc_proto_v1_delivery_delivery_proto = out.File
	file_server_grpc_proto_v1_delivery_delivery_proto_goTypes = nil
	file_server_grpc_proto_v1_delivery_delivery_proto_depIdxs = nil
}
